development:
  adapter: postgresql
  schema_search_path: "public,shared_extensions"
  encoding: utf8
  host: 127.0.0.1
  pool: 20
  username: reactrails
  password: password1
  database: myprojectgpt
  timeout: 5000
